[package]
name = "rust-notes"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "4.0"
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.8"
